name: Release Standalone

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: RcloneWebuiAngular-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            RcloneWebuiAngular-${{ runner.os }}-node-

      - name: Build
        run: |
          npm clean-install
          sed -i 's/"baseHref": "\(.*\)"/"baseHref": "rclone-webui-angular\/\1"/g' ./angular.json
          npm run build:standalone
          cp src/i18n-index.html dist/build/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/build

      - name: Deploy to Github-Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
